import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../../components/Header";
import { ReduxProvider } from "../../storeRedux/reduxProvider";
import { Suspense } from "react";
import { IconTomato } from "./icons";

export const metadata: Metadata = {
  title: "pomodorix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="ru">
        <body>
          <Header />
          <main>
            {children}
          </main>
          <div id="modal-root" />
        </body>
      </html>
    </ReduxProvider>
  );
}
